
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 29 18:23:19 GFT 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 19;
  public static final int Parentesis_abertura = 28;
  public static final int Divisao = 25;
  public static final int Begin = 8;
  public static final int End = 9;
  public static final int Util = 15;
  public static final int Op_booleano = 27;
  public static final int All = 17;
  public static final int Repeat = 16;
  public static final int If = 10;
  public static final int Maior = 34;
  public static final int Diferente = 38;
  public static final int Real = 6;
  public static final int Op_relacionais = 26;
  public static final int Menor = 35;
  public static final int Else = 12;
  public static final int P_virgula = 32;
  public static final int Then = 11;
  public static final int T_dado = 2;
  public static final int Menor_Ingual = 36;
  public static final int While = 13;
  public static final int Int = 4;
  public static final int Atribuicao = 33;
  public static final int EOF = 0;
  public static final int And = 18;
  public static final int error = 1;
  public static final int Integer = 5;
  public static final int Linha = 7;
  public static final int Maior_Ingual = 37;
  public static final int Soma = 22;
  public static final int ERROR = 41;
  public static final int Do = 14;
  public static final int Virgula = 31;
  public static final int String = 3;
  public static final int Identificador = 39;
  public static final int Programa_inicio = 20;
  public static final int Ponto = 30;
  public static final int Numero = 40;
  public static final int Igual = 21;
  public static final int Multiplica = 24;
  public static final int Subtracao = 23;
  public static final int Parentesis_fechar = 29;
}

