
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 28 21:48:33 GFT 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 20;
  public static final int Parentesis_abertura = 29;
  public static final int Divisao = 26;
  public static final int Begin = 8;
  public static final int End = 9;
  public static final int Util = 16;
  public static final int Op_booleano = 28;
  public static final int All = 18;
  public static final int Repeat = 17;
  public static final int If = 11;
  public static final int Maior = 34;
  public static final int Diferente = 38;
  public static final int Real = 5;
  public static final int Op_relacionais = 27;
  public static final int Menor = 35;
  public static final int Else = 13;
  public static final int P_virgula = 32;
  public static final int Then = 12;
  public static final int T_dado = 2;
  public static final int Menor_Ingual = 36;
  public static final int While = 14;
  public static final int Int = 3;
  public static final int Atribuicao = 33;
  public static final int EOF = 0;
  public static final int And = 19;
  public static final int Nome = 10;
  public static final int error = 1;
  public static final int Integer = 4;
  public static final int Linha = 7;
  public static final int Maior_Ingual = 37;
  public static final int Soma = 23;
  public static final int ERROR = 42;
  public static final int Do = 15;
  public static final int String = 6;
  public static final int Identificador = 40;
  public static final int Ponto = 31;
  public static final int Numero = 41;
  public static final int Program = 21;
  public static final int Igual = 22;
  public static final int Multiplica = 25;
  public static final int Subtracao = 24;
  public static final int Parentesis_fechar = 30;
  public static final int Comillas = 39;
}

